## Data Selection in Series

A **series** object acts in many ways like a one dimensional Numpy array and in many ways like a standard python dictionary

### Series as Dictionary

The **series** provide a mapping from a collection of keys to a collection of values

In [1]:
import pandas as pd

data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [2]:
data['b']

np.float64(0.5)

In [3]:
'a' in data

True

In [4]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [5]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [6]:
## series objects can also be modified with a dictionary-like syntax

data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

## Series as One-Dimensional Array

A **Series** builds on this dictionary like interface and provide array style item selection via the same basic mechanism as Numpy array-that is slices, masking and fancing indexing

In [7]:
# slicing by explicit indexing
data['a':'d']

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [8]:
# slicing by implicit indexing
data[0:2]

a    0.25
b    0.50
dtype: float64

In [9]:
# masking
data[(data > 0.3) & (data < 1.0)]

b    0.50
c    0.75
dtype: float64

In [10]:
# fancy indexing
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

## Indexers: Loc & Iloc

Pandas provides some special **indexer** attributes expose certain indexing schemas

In [11]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [12]:
# explicit indexing
data[1]

'a'

In [13]:
# implicit indexing
data[1:3]

3    b
5    c
dtype: object

The **Loc** attribute allows indexing and slicing that always refrencing the explicit index

In [14]:
data.loc[1]

'a'

In [15]:
data.loc[1:3]

1    a
3    b
dtype: object

The **iloc** attributes allows indexing and slicing that always refrences the implicit python style index

In [16]:
data.iloc[1]

'b'

In [17]:
data.iloc[1:3]

3    b
5    c
dtype: object

## Data Selection in DataFrames

## DataFrame as Dictionary

We will consider **Dataframe** as a dictionary of related Series objects.

In [18]:
area = pd.Series({'California': 423967, 'Texas': 695662, 'Florida': 170312, 'New York': 141297, 'Pennsylvenia': 119280})
pop = pd.Series({'California': 39538223, 'Texas': 29145505, 'Florida': 21538187, 'New York': 20201249, 'Pennsylvenia': 13002700})

data = pd.DataFrame({'area': area, 'pop': pop})
data

                area       pop
California    423967  39538223
Texas         695662  29145505
Florida       170312  21538187
New York      141297  20201249
Pennsylvenia  119280  13002700

In [19]:
data['area']

California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvenia    119280
Name: area, dtype: int64

In [20]:
data.area

California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvenia    119280
Name: area, dtype: int64

In [21]:
data['density'] = data['pop'] / data['area']
data

                area       pop     density
California    423967  39538223   93.257784
Texas         695662  29145505   41.896072
Florida       170312  21538187  126.463121
New York      141297  20201249  142.970120
Pennsylvenia  119280  13002700  109.009893

To avoid temptation to try column assignment via attributes (use **data['pop'] = z** rather than **data.pop = z**)

## Dataframe as Two Dimensional Array

In [22]:
data.values

array([[4.23967000e+05, 3.95382230e+07, 9.32577842e+01],
       [6.95662000e+05, 2.91455050e+07, 4.18960717e+01],
       [1.70312000e+05, 2.15381870e+07, 1.26463121e+02],
       [1.41297000e+05, 2.02012490e+07, 1.42970120e+02],
       [1.19280000e+05, 1.30027000e+07, 1.09009893e+02]])

In [23]:
data.T # transpose row and column

           California         Texas       Florida      New York  Pennsylvenia
area     4.239670e+05  6.956620e+05  1.703120e+05  1.412970e+05  1.192800e+05
pop      3.953822e+07  2.914550e+07  2.153819e+07  2.020125e+07  1.300270e+07
density  9.325778e+01  4.189607e+01  1.264631e+02  1.429701e+02  1.090099e+02

In [24]:
data.values[0]

array([4.23967000e+05, 3.95382230e+07, 9.32577842e+01])

In [26]:
data.iloc[:3, :2]

              area       pop
California  423967  39538223
Texas       695662  29145505
Florida     170312  21538187

In [28]:
data.loc[:'Florida', :'pop']

              area       pop
California  423967  39538223
Texas       695662  29145505
Florida     170312  21538187

In [29]:
data[data.density > 120]

            area       pop     density
Florida   170312  21538187  126.463121
New York  141297  20201249  142.970120