## Trade Offs in Missing Data Converntions

To track the presence of missing data in a table or dataframes, they generally revolve around one of two strategy: 1) **mask** that globally missing values , 2) **sentinal values** that indicates a missing entry


Pandas has two modes of storing and manipulating null values:-

1) The default mode is to use a sentinel based missing data scheme with sentinel values **NAN OR NONE** depanding on the type of the data.

2) we can opt in to using the nullable data tupes pandas providing which results in the creation an accompanied mask array to track missing values

In [1]:
import pandas as pd
import numpy as np

## None as Sentinel Value


For some data types, pandas uses None as sentinel values. **None** is python object

In [2]:
vals1 = np.array([1, 2, None, 3])
vals1

array([1, 2, None, 3], dtype=object)

In [4]:
 # vals1.sum()

## NaN: Missing Numerical Data

NaN is different, it is a special floating point value recognized by all systems that use the standard IEEE floating point representation.

In [6]:
vals2 = np.array([1, np.nan, 2, 3, 4])
vals2

# Nan is a bit like data virus it infects any other bjects it touches

array([ 1., nan,  2.,  3.,  4.])

In [7]:
1 + np.nan

nan

In [8]:
vals2.sum(), vals2.min(), vals2.max()

(np.float64(nan), np.float64(nan), np.float64(nan))

In [9]:
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2)

(np.float64(10.0), np.float64(1.0), np.float64(4.0))

## NaN and None in Pandas

In [10]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [11]:
x = pd.Series(range(2), dtype=int)
x

0    0
1    1
dtype: int64

In [13]:
x[0] = None
x

0    NaN
1    1.0
dtype: float64

## Pandas Nullable Dtypes

Previously there is no way to represent a true integer array with missing data.

Pandas added **nullable dtypes**  (eg:- pd.Int32)

In [14]:
pd.Series([1, np.nan, 2, None, pd.NA], dtype='Int32')

0       1
1    <NA>
2       2
3    <NA>
4    <NA>
dtype: Int32

## Operation on Null Values

1) **isnull** :- Generates a boolean mask indicating missing values

2) **notnull**:- opposite of isnull

3) **dropna** :- Returned a filtered version of data

4) **fillna** :- Return a copy of the data with missing values filled or imputed

In [15]:
data = pd.Series([1, np.nan, 'hello', None])

In [16]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [17]:
data[data.isnull()]

1     NaN
3    None
dtype: object

In [18]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [19]:
data.dropna()

0        1
2    hello
dtype: object

In [20]:
df = pd.DataFrame([[1, np.nan, 2],
                   [2, 3, 5],
                   [np.nan, 4, 6]])
df

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [21]:
df.dropna()
## we cannot drop single value in dataframe

     0    1  2
1  2.0  3.0  5

In [22]:
df.dropna(axis='columns')

   2
0  2
1  5
2  6

In [23]:
df[3] = np.nan
df

     0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [24]:
df.dropna(axis='columns', how='all')
## how='all' only drop rows and colums that contains null values

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [25]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'), dtype='Int32')
data

a       1
b    <NA>
c       2
d    <NA>
e       3
dtype: Int32

In [26]:
data.fillna(0)
## fill NA entries with a single value such as zero

a    1
b    0
c    2
d    0
e    3
dtype: Int32

In [27]:
# forward fill
data.fillna(method='ffill')

/tmp/ipykernel_1187/3988156040.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill')

a    1
b    1
c    2
d    2
e    3
dtype: Int32

In [28]:
# back fill
data.fillna(method='bfill')

/tmp/ipykernel_1187/3243020708.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='bfill')

a    1
b    2
c    2
d    3
e    3
dtype: Int32

In [29]:
df

     0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [30]:
df.fillna(method='ffill', axis=1)

/tmp/ipykernel_1187/901808322.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', axis=1)

     0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0