In [1]:
import numpy as np
import pandas as pd

## A Multiply Indexed Series

In [2]:
index = [('california', 2010), ('california', 2020), ('New York', 2010), ('New York', 2020), ('Texas', 2010), ('Texas', 2020)]
populations = [37253956, 39538223, 19378102, 20201249, 25145561, 29145505]
pop = pd.Series(populations, index=index)
pop

(california, 2010)    37253956
(california, 2020)    39538223
(New York, 2010)      19378102
(New York, 2020)      20201249
(Texas, 2010)         25145561
(Texas, 2020)         29145505
dtype: int64

In [3]:
pop[[i for i in pop.index if i[1] == 2010]]

(california, 2010)    37253956
(New York, 2010)      19378102
(Texas, 2010)         25145561
dtype: int64

## The Better Way: The Pandas MultiIndex

In [4]:
index = pd.MultiIndex.from_tuples(index)
# Multiindex represents multiple level of indexing

In [5]:
pop = pop.reindex(index)
pop

california  2010    37253956
            2020    39538223
New York    2010    19378102
            2020    20201249
Texas       2010    25145561
            2020    29145505
dtype: int64

In [6]:
pop[:, 2020]

california    39538223
New York      20201249
Texas         29145505
dtype: int64

## MultiIndex as Extra Dimension

The **unstack** method will quickly convert a multiply indexed series into a conventionally indexed Dataframes

The **stack** method provide the opposite operations

In [7]:
pop_df = pop.unstack()
pop_df

                2010      2020
New York    19378102  20201249
Texas       25145561  29145505
california  37253956  39538223

In [8]:
pop_df.stack()

New York    2010    19378102
            2020    20201249
Texas       2010    25145561
            2020    29145505
california  2010    37253956
            2020    39538223
dtype: int64

In [9]:
pop_df = pd.DataFrame({'total': pop,
                       'Under 18': [9284094, 8898092,
                                    4318033, 4181528,
                                    6879014, 7432474]})
pop_df

                    total  Under 18
california 2010  37253956   9284094
           2020  39538223   8898092
New York   2010  19378102   4318033
           2020  20201249   4181528
Texas      2010  25145561   6879014
           2020  29145505   7432474

In [10]:
f_u18 = pop_df['Under 18'] / pop_df['total']
f_u18.unstack()

                2010      2020
New York    0.222831  0.206994
Texas       0.273568  0.255013
california  0.249211  0.225050

## Method of Multiindex Creation

The most straightforward way to create a multiply indexed series or dataframes is to simply pass a list of two or more index arrays to the constructor

In [11]:
df = pd.DataFrame(np.random.rand(4,2),
                  index=[['a','a', 'b', 'b'], [1,2,1,2]],
                  columns=['data1', 'data2'])
df

        data1     data2
a 1  0.889354  0.225510
  2  0.027012  0.582566
b 1  0.240476  0.188670
  2  0.093908  0.701062

## Explicit MultiIndex Constructors

In [12]:
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b'], [1, 2, 1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [13]:
pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [14]:
pd.MultiIndex.from_product([['a', 'b'], [1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [15]:
pd.MultiIndex(levels=[['a', 'b'], [1, 2]],
              codes=[[0, 0, 1, 1], [0, 1, 0, 1]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

## MultiIndex level Names

In [16]:
pop.index.names = ['state', 'year']
pop

state       year
california  2010    37253956
            2020    39538223
New York    2010    19378102
            2020    20201249
Texas       2010    25145561
            2020    29145505
dtype: int64

## MultiIndex for columns

In Dataframes, row and columns are completely symmetric

In [17]:
# hierarchial indices and columns
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]],
                                   names=['year', 'visit'])
columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']],
                                     names=['subject', 'type'])

data = np.round(np.random.randn(4, 6), 1)
data[:, ::2] *= 10
data += 37

health_data = pd.DataFrame(data=data, index=index, columns=columns)
health_data

subject      Bob       Guido         Sue
type          HR  Temp    HR  Temp    HR  Temp
year visit
2013 1      44.0  35.7  41.0  37.7  35.0  37.5
     2      47.0  38.1  31.0  36.8  39.0  38.6
2014 1      39.0  37.2  33.0  36.3  46.0  36.7
     2      49.0  36.3  37.0  37.9  41.0  35.8

In [18]:
health_data['Guido']

type          HR  Temp
year visit
2013 1      41.0  37.7
     2      31.0  36.8
2014 1      33.0  36.3
     2      37.0  37.9

## Indexing and Slicing a Multiindex

In [19]:
pop

state       year
california  2010    37253956
            2020    39538223
New York    2010    19378102
            2020    20201249
Texas       2010    25145561
            2020    29145505
dtype: int64

In [21]:
pop['california', 2010]

np.int64(37253956)

In [26]:
#pop.loc['california':'New York']

## Multiply Indexed DataFrames

In [27]:
health_data

subject      Bob       Guido         Sue
type          HR  Temp    HR  Temp    HR  Temp
year visit
2013 1      44.0  35.7  41.0  37.7  35.0  37.5
     2      47.0  38.1  31.0  36.8  39.0  38.6
2014 1      39.0  37.2  33.0  36.3  46.0  36.7
     2      49.0  36.3  37.0  37.9  41.0  35.8

In [28]:
health_data.iloc[:2, :2]

subject      Bob
type          HR  Temp
year visit
2013 1      44.0  35.7
     2      47.0  38.1

In [29]:
idx = pd.IndexSlice
health_data.loc[idx[:, 1], idx[:, 'HR']]

subject      Bob Guido   Sue
type          HR    HR    HR
year visit
2013 1      44.0  41.0  35.0
2014 1      39.0  33.0  46.0

## Rearranging Multi-Indexes

### Sorted and Unsorted Indices

Many of the MultiIndex slicing will fail if the index is not sorted.

In [30]:
index = pd.MultiIndex.from_product([['a', 'b', 'c'], [1,2]])
data = pd.Series(np.random.rand(6), index=index)
data.index.names = ['char', 'int']
data

char  int
a     1      0.545753
      2      0.185570
b     1      0.096944
      2      0.668937
c     1      0.321691
      2      0.089983
dtype: float64

In [34]:
try:
  data['a': 'b']
except KeyError as e:
  print("KeyError", e)

In [35]:
data = data.sort_index()
data

char  int
a     1      0.545753
      2      0.185570
b     1      0.096944
      2      0.668937
c     1      0.321691
      2      0.089983
dtype: float64

In [36]:
data['a': 'b']

char  int
a     1      0.545753
      2      0.185570
b     1      0.096944
      2      0.668937
dtype: float64

## Stacking and Unstacking Indices

In [37]:
pop.unstack(level=0)

state  New York     Texas  california
year
2010   19378102  25145561    37253956
2020   20201249  29145505    39538223

In [38]:
pop.unstack(level=1)

year            2010      2020
state
New York    19378102  20201249
Texas       25145561  29145505
california  37253956  39538223

In [39]:
pop.unstack().stack()

state       year
New York    2010    19378102
            2020    20201249
Texas       2010    25145561
            2020    29145505
california  2010    37253956
            2020    39538223
dtype: int64

## Index Setting and Resetting

In [40]:
pop_flat = pop.reset_index(name='population')
pop_flat

        state  year  population
0  california  2010    37253956
1  california  2020    39538223
2    New York  2010    19378102
3    New York  2020    20201249
4       Texas  2010    25145561
5       Texas  2020    29145505

In [41]:
pop_flat.set_index(['state', 'year'])

                 population
state      year
california 2010    37253956
           2020    39538223
New York   2010    19378102
           2020    20201249
Texas      2010    25145561
           2020    29145505