## The Pandas Series Object

A **Pandas Series** is a one dimensional array of indexed data. It can be created from a list or array

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.Series([.25, .05, .75, 1.5])
data

0    0.25
1    0.05
2    0.75
3    1.50
dtype: float64

**Series** combines a sequence of values with an explicit sequence of indices which we can access with the values and index attributes

In [3]:
data.values

array([0.25, 0.05, 0.75, 1.5 ])

In [4]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
data[1] # same for accessing data

np.float64(0.05)

## Series as Generalized Numpy Array

Numpy array has an implicitly defined integer index used to access the values the pandas series has an explicitly defined index associated with values

In [6]:
data = pd.Series([0.25, 0.50, 0.75, 1.1], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.10
dtype: float64

In [7]:
data['a']

np.float64(0.25)

## Series as Specialized Dictionary

A dictionary is a structure that maps typed arbitrary keys to a set of arbitrary values, and a Series is a structure that maps typed keys to a set of typed values.

The type inforamtion of a pandas series makes it more efficient than python dictionaries for certain operations

In [8]:
population_dict = {'California': 39538223, 'Texas': 26448193, 'New York': 19651127, 'Florida': 21538187, 'Pennsylvania': 12802503 }
population = pd.Series(population_dict)
population

California      39538223
Texas           26448193
New York        19651127
Florida         21538187
Pennsylvania    12802503
dtype: int64

In [9]:
population['California']

np.int64(39538223)

## The Pandas DataFrame object

the **DataFrame** can be thought of either as a generalization of a Numpy array or as a specialization of a python dictionary

### DataFrame as Generalized Numpy array

A **Dataframe** is an analog of a two dimensional array with explicit row and column indices.

**Dataframe** as a sequence of aligned series objects.

In [10]:
area_dict = {'California': 423967, 'Texas': 695662, 'Florida': 170312, 'New York': 141297, 'Pennsylvania': 119280}
area = pd.Series(area_dict)
area

California      423967
Texas           695662
Florida         170312
New York        141297
Pennsylvania    119280
dtype: int64

In [11]:
states = pd.DataFrame({'population': population, 'area': area})
states

              population    area
California      39538223  423967
Florida         21538187  170312
New York        19651127  141297
Pennsylvania    12802503  119280
Texas           26448193  695662

In [12]:
states.index

Index(['California', 'Florida', 'New York', 'Pennsylvania', 'Texas'], dtype='object')

In [13]:
states.columns

Index(['population', 'area'], dtype='object')

**Dataframe** can be thought as a generalization of a two dimensional numpy array, where both row and columns have a generalized  index for accessing the data.

## Constructing Dataframe Objects

## From a single Series object

A **Dataframe** is a collection of series objects, and a single column dataframe can be constructed from a single series

In [14]:
pd.DataFrame(population, columns=['population'])

              population
California      39538223
Texas           26448193
New York        19651127
Florida         21538187
Pennsylvania    12802503

## From a list of dicts

Any list of dictionaries can be made into a Dataframe

In [15]:
data = [{'a': i, 'b': 2 * i}
        for i in range(3)]
pd.DataFrame(data)

   a  b
0  0  0
1  1  2
2  2  4

## From a two dimensional Numpy array

In [16]:
pd.DataFrame(np.random.rand(3, 2), columns=['foo', 'bar'], index=['a', 'b', 'c'])

        foo       bar
a  0.434691  0.370893
b  0.992970  0.963667
c  0.228908  0.991693

## From a Numpy structured array

A pandas  dataframe operates much like a structured array, can be directly from one

In [17]:
A = np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [18]:
pd.DataFrame(A)

   A    B
0  0  0.0
1  0  0.0
2  0  0.0

In [19]:
ind = pd.Index([2,3,5,7,9])
ind

Index([2, 3, 5, 7, 9], dtype='int64')

In [20]:
ind[1]

np.int64(3)

In [21]:
ind[::2]

Index([2, 5, 9], dtype='int64')

In [23]:
ind[1] = 0 # index is an immutable array

np.int64(3)

In [24]:
indA = pd.Index([1,3,5,7,9])
indB = pd.Index([2,3,5,7,11])

In [25]:
indA.intersection(indB)

Index([3, 5, 7], dtype='int64')

In [26]:
indA.union(indB)

Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [27]:
indA.symmetric_difference(indB)

Index([1, 2, 9, 11], dtype='int64')