## Ufuncs : Index Preservation

Pandas is designed to work with Numpy, any Numpy ufuncs will work on Pandas Series and DataFrame objects.

In [2]:
import pandas as pd
import numpy as np

In [3]:
rng = np.random.default_rng(42)
ser = pd.Series(rng.integers(0, 10, 4))
ser

0    0
1    7
2    6
3    4
dtype: int64

In [4]:
df = pd.DataFrame(rng.integers(0, 10, (3, 4)),
                  columns=['A', 'B', 'C', 'D'])
df

   A  B  C  D
0  4  8  0  6
1  2  0  5  9
2  7  7  7  7

In [5]:
np.exp(ser)

0       1.000000
1    1096.633158
2     403.428793
3      54.598150
dtype: float64

In [6]:
np.sin(df * np.pi / 4)

              A             B         C         D
0  1.224647e-16 -2.449294e-16  0.000000 -1.000000
1  1.000000e+00  0.000000e+00 -0.707107  0.707107
2 -7.071068e-01 -7.071068e-01 -0.707107 -0.707107

## Ufuncs : Index Alignment

For binary operation on two **Series** or **Dataframe** objects, Pandas will align indices in the process of performing the operation.

### Index Alignment in Series

In [7]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')
population = pd.Series({'California': 39538223, 'Texas': 29752201,
                        'Florida': 21538187}, name='population')

In [8]:
population / area

Alaska              NaN
California    93.257784
Florida             NaN
Texas         42.768185
dtype: float64

In [9]:
area.index.union(population.index)

Index(['Alaska', 'California', 'Florida', 'Texas'], dtype='object')

In [10]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [11]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

## Index Alignment in DataFrames

A similar type of alignment takes place for both columns and indices when performing operation on **DataFrame** objects.

In [13]:
A = pd.DataFrame(rng.integers(0, 20, (2, 2)),
                 columns=['A', 'B'])
A

    A   B
0  10   7
1   3  18

In [14]:
B = pd.DataFrame(rng.integers(0, 10, (3, 3)),
                 columns=['B', 'A', 'C'])
B

   B  A  C
0  7  6  4
1  8  5  4
2  4  2  0

In [15]:
A + B

      A     B   C
0  16.0  14.0 NaN
1   8.0  26.0 NaN
2   NaN   NaN NaN

In [16]:
A.add(B, fill_value=A.values.mean())

      A     B     C
0  16.0  14.0  13.5
1   8.0  26.0  13.5
2  11.5  13.5   9.5

## Ufuncs: Operation Between DataFrames and Series

when performing operations b/w a Dataframe and a Series, the index and column alignment is similarly maintained and the result is similar to operations between a two dimensional and one dimensional Numpy array

In [17]:
A = rng.integers(10, size=(3,4))
A

array([[5, 8, 0, 8],
       [8, 2, 6, 1],
       [7, 7, 3, 0]])

In [18]:
A - A[0]

array([[ 0,  0,  0,  0],
       [ 3, -6,  6, -7],
       [ 2, -1,  3, -8]])

In [19]:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0]

   Q  R  S  T
0  0  0  0  0
1  3 -6  6 -7
2  2 -1  3 -8

In [20]:
# for column wise
df.subtract(df['R'], axis=0)

   Q  R  S  T
0 -3  0 -8  0
1  6  0  4 -1
2  0  0 -4 -7

In [21]:
halfrow = df.iloc[0, ::2]
halfrow

Q    5
S    0
Name: 0, dtype: int64

In [22]:
df - halfrow

     Q   R    S   T
0  0.0 NaN  0.0 NaN
1  3.0 NaN  6.0 NaN
2  2.0 NaN  3.0 NaN